---
 - name: nfs server
   hosts: ec2-52-66-196-127.ap-south-1.compute.amazonaws.com
   tasks:
    
    - name: install software
      dnf:
        name: nfs-utils
        state: present

    - name: start and enable service
      service:
        name: nfs-server
        state: started
        enabled: yes

    - name: create a share dir
      file:
        path: /share1
        state: directory

    - name: manage configuration
      lineinfile:
        path: /etc/exports
        line: '/share1   ec2-13-232-108-14.ap-south-1.compute.amazonaws.com(ro)'
        state: present

    - name: update
      shell:
        cmd: exportfs -r

 - name: nfs client
   hosts: ec2-13-232-108-14.ap-south-1.compute.amazonaws.com
   tasks:
    
    - name: install software
      dnf: 
        name: nfs-utils
        state: present

    - name: mount the share
      mount:
        src: ec2-52-66-196-127.ap-south-1.compute.amazonaws.com:/share1
        path: /local1
        state: mounted
        fstype: nfs

